[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "chainlink/=lib/chainlink/",
    "forge-std/=lib/forge-std/src/",
]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

[rpc_endpoints]
mainnet = "${ETH_MAINNET_RPC}"

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 64 }